# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: ./cmd/spire-ha-agent
    binary: spire-ha-agent
    id: spire-ha-agent
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: ./cmd/spire-trust-sync-helper
    binary: spire-trust-sync-helper
    id: spire-trust-sync-helper

archives:
  - format: tar.gz
    builds:
      - spire-ha-agent
    id: spire-ha-agent
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      spire-ha-agent_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - systemd/spire-ha-agent@.service
      - systemd/spire-socat@.service
      - README.md
      - LICENSE
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
  - format: tar.gz
    builds:
      - spire-trust-sync-helper
    id: spire-trust-sync-helper
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      spire-trust-sync-helper_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - systemd/spire-trust-sync@.service  
      - config/trust-sync/default.conf
      - README.md
      - LICENSE
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

kos:
  - repositories:
      - ghcr.io/spiffe/spire-ha-agent
    tags:
      - "{{.Version}}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
